### ISSUE TITLE
Minor translation error (Dutch/NL)

### ISSUE THREAD

**Issue by R0GGER** [bigbluebutton/greenlight#1062]
Translation for signup is now 'Aanmelden' and should be 'Registreren'.

File: config/locales/nl.yml
Line: 535

```
  signup:
    password_confirm: Wachtwoordbevestiging
    subtitle: Account aanmaken
    title: Aanmelden
    with: "Meld u aan bij %{provider}"
```

Should be:
```
  signup:
    password_confirm: Wachtwoordbevestiging
    subtitle: Account aanmaken
    title: Registreren
    with: "Meld u aan bij %{provider}"
```
