### ISSUE TITLE
Switch from bbb-install to customize install docker-compose doesn't work

### ISSUE THREAD

**Issue by hosseinhashemidev** [bigbluebutton/greenlight#1528]
Hi Guys

I've installed the BBB/Greenlight on Contabo VPS with **bbb-install.sh** and everything work well.
Now, I need to customize the greenlight. So I followed the documentation:

"**Switching from Install to Customize**"
http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

But now on step 5 (according to the documentation) when I want to start GreenLight Docker-Compose returns error:
Also when I open the bigblubutton URL it shows error 404 both URL ( the main URL and /b)

```
root@yyyyy:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Pulling app (mycustomimage/greenlight:v2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```

- Here is my docker-compose.yml:

```
version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: mycustomimage/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

```

well, when I enter docker-compose images it shows:
```

root@yyyyy:~/greenlight# docker-compose images
Container   Repository   Tag   Image Id   Size
----------------------------------------------
```

Also for when enter docker-compose ps it shows:
```
root@yyyyy:~/greenlight# docker-compose ps
Name   Command   State   Ports
------------------------------
```

But when enter the docker images  it shows:
```

root@yyyyy:~/greenlight# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
mycustomimage              release-v2          d9222c126f1c        20 minutes ago      198MB
<none>                     <none>              ecd8bcec9d1a        20 minutes ago      412MB
hossein                    release-v2          c510f5a264fc        11 hours ago        198MB
<none>                     <none>              8ae438c93642        11 hours ago        412MB
<none>                     <none>              06bf20898ec0        12 hours ago        198MB
<none>                     <none>              b2ead3fb086b        12 hours ago        412MB
hosseinimage               release-v2          f1a135724f32        42 hours ago        198MB
<none>                     <none>              452237fa6734        42 hours ago        412MB
<none>                     <none>              6b7e3d770656        42 hours ago        198MB
<none>                     <none>              3f8b691f7e65        42 hours ago        412MB
myimage                    release-v2          4c40d8727a0b        46 hours ago        198MB
<none>                     <none>              8d54b124b16d        46 hours ago        412MB
postgres                   9.5                 ae83c6861279        12 days ago         197MB
bigbluebutton/greenlight   v2                  4ffc5433e7c1        13 days ago         198MB
ruby                       2.5.1-alpine        d29267791323        19 months ago       45.3MB
```

As you can see, **mycustomimage** is available on the list.
Now, could you please help me how can I fix the issue?
I tried to add all information, in case you need any log please let me know.
